export const manufacturer = 
{
    "manufacturers": [
        {
            "id": 11,
            "url": "https://demo.netbox.dev/api/dcim/manufacturers/11/",
            "display": "APC",
            "name": "APC",
            "slug": "apc",
            "description": "",
            "tags": [],
            "custom_fields": {},
            "created": "2020-12-22T00:00:00Z",
            "last_updated": "2020-12-22T02:25:37.151000Z",
            "devicetype_count": 1,
            "inventoryitem_count": 0,
            "platform_count": 0
        },
        {
            "id": 1,
            "url": "https://demo.netbox.dev/api/dcim/manufacturers/1/",
            "display": "Arista",
            "name": "Arista",
            "slug": "arista",
            "description": "",
            "tags": [],
            "custom_fields": {},
            "created": "2020-12-18T00:00:00Z",
            "last_updated": "2020-12-18T03:17:05.204000Z",
            "devicetype_count": 0,
            "inventoryitem_count": 0,
            "platform_count": 0
        },
        {
            "id": 2,
            "url": "https://demo.netbox.dev/api/dcim/manufacturers/2/",
            "display": "Brocade",
            "name": "Brocade",
            "slug": "brocade",
            "description": "",
            "tags": [],
            "custom_fields": {},
            "created": "2020-12-18T00:00:00Z",
            "last_updated": "2020-12-18T03:17:05.246000Z",
            "devicetype_count": 0,
            "inventoryitem_count": 0,
            "platform_count": 0
        },
        {
            "id": 3,
            "url": "https://demo.netbox.dev/api/dcim/manufacturers/3/",
            "display": "Cisco",
            "name": "Cisco",
            "slug": "cisco",
            "description": "",
            "tags": [],
            "custom_fields": {},
            "created": "2020-12-18T00:00:00Z",
            "last_updated": "2020-12-18T03:17:05.280000Z",
            "devicetype_count": 2,
            "inventoryitem_count": 0,
            "platform_count": 1
        },
        {
            "id": 4,
            "url": "https://demo.netbox.dev/api/dcim/manufacturers/4/",
            "display": "Dell",
            "name": "Dell",
            "slug": "dell",
            "description": "",
            "tags": [],
            "custom_fields": {},
            "created": "2020-12-18T00:00:00Z",
            "last_updated": "2020-12-18T03:17:05.307000Z",
            "devicetype_count": 0,
            "inventoryitem_count": 0,
            "platform_count": 0
        },
        {
            "id": 5,
            "url": "https://demo.netbox.dev/api/dcim/manufacturers/5/",
            "display": "Extreme",
            "name": "Extreme",
            "slug": "extreme",
            "description": "",
            "tags": [],
            "custom_fields": {},
            "created": "2020-12-18T00:00:00Z",
            "last_updated": "2020-12-18T03:17:05.335000Z",
            "devicetype_count": 0,
            "inventoryitem_count": 0,
            "platform_count": 0
        },
        {
            "id": 6,
            "url": "https://demo.netbox.dev/api/dcim/manufacturers/6/",
            "display": "F5",
            "name": "F5",
            "slug": "f5",
            "description": "",
            "tags": [],
            "custom_fields": {},
            "created": "2020-12-18T00:00:00Z",
            "last_updated": "2020-12-18T03:17:05.359000Z",
            "devicetype_count": 0,
            "inventoryitem_count": 0,
            "platform_count": 0
        },
        {
            "id": 13,
            "url": "https://demo.netbox.dev/api/dcim/manufacturers/13/",
            "display": "Generic",
            "name": "Generic",
            "slug": "generic",
            "description": "",
            "tags": [],
            "custom_fields": {},
            "created": "2021-04-02T00:00:00Z",
            "last_updated": "2021-04-02T17:11:48.340000Z",
            "devicetype_count": 1,
            "inventoryitem_count": 0,
            "platform_count": 0
        },
        {
            "id": 7,
            "url": "https://demo.netbox.dev/api/dcim/manufacturers/7/",
            "display": "Juniper",
            "name": "Juniper",
            "slug": "juniper",
            "description": "",
            "tags": [],
            "custom_fields": {},
            "created": "2020-12-18T00:00:00Z",
            "last_updated": "2020-12-18T03:17:05.383000Z",
            "devicetype_count": 7,
            "inventoryitem_count": 0,
            "platform_count": 0
        },
        {
            "id": 14,
            "url": "https://demo.netbox.dev/api/dcim/manufacturers/14/",
            "display": "Lenovo",
            "name": "Lenovo",
            "slug": "lenovo",
            "description": "",
            "tags": [],
            "custom_fields": {},
            "created": "2022-01-10T00:00:00Z",
            "last_updated": "2022-01-10T20:58:27.504000Z",
            "devicetype_count": 1,
            "inventoryitem_count": 0,
            "platform_count": 0
        },
        {
            "id": 8,
            "url": "https://demo.netbox.dev/api/dcim/manufacturers/8/",
            "display": "Opengear",
            "name": "Opengear",
            "slug": "opengear",
            "description": "",
            "tags": [],
            "custom_fields": {},
            "created": "2020-12-18T00:00:00Z",
            "last_updated": "2020-12-18T03:17:05.407000Z",
            "devicetype_count": 0,
            "inventoryitem_count": 0,
            "platform_count": 0
        },
        {
            "id": 9,
            "url": "https://demo.netbox.dev/api/dcim/manufacturers/9/",
            "display": "Palo Alto",
            "name": "Palo Alto",
            "slug": "palo-alto",
            "description": "",
            "tags": [],
            "custom_fields": {},
            "created": "2020-12-18T00:00:00Z",
            "last_updated": "2020-12-18T03:17:05.431000Z",
            "devicetype_count": 0,
            "inventoryitem_count": 0,
            "platform_count": 0
        },
        {
            "id": 12,
            "url": "https://demo.netbox.dev/api/dcim/manufacturers/12/",
            "display": "Panduit",
            "name": "Panduit",
            "slug": "panduit",
            "description": "",
            "tags": [],
            "custom_fields": {},
            "created": "2020-12-30T00:00:00Z",
            "last_updated": "2020-12-30T20:35:02.867000Z",
            "devicetype_count": 2,
            "inventoryitem_count": 0,
            "platform_count": 0
        },
        {
            "id": 10,
            "url": "https://demo.netbox.dev/api/dcim/manufacturers/10/",
            "display": "Ubiquiti",
            "name": "Ubiquiti",
            "slug": "ubiquiti",
            "description": "",
            "tags": [],
            "custom_fields": {},
            "created": "2020-12-18T00:00:00Z",
            "last_updated": "2020-12-18T03:17:05.470000Z",
            "devicetype_count": 0,
            "inventoryitem_count": 0,
            "platform_count": 0
        }
    ]
};