name: Create JS file from JSON

on: [push, workflow_dispatch] 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install jq

    - name: Run script
      run: |
        echo "export const mapping = $(jq -c . < src/schema.jsm.json);" > src/mapping.js

    - name: Commit and push if it's not a pull request
      if: github.event_name != 'pull_request'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add src/mapping.js
        if git diff --quiet HEAD; then
          echo "No changes to commit"
        else
          git commit -m "Update mapping.js" -a
          git push
        fi