name: Create JS mapping file from JSON schema

on: 
  workflow_dispatch:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Remove existing mapping.js if it exists
      run: |
        if [ -f src/mapping.js ]; then
          rm src/mapping.js
        fi

    - name: Generate mapping.js from schema.jsm.json
      run: |
        echo "export const mapping = $(jq -c . < src/schema.jsm.json);" > src/mapping.js
