name: Create JS file from JSON

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Remove existing mapping.js if it exists
      run: |
        if [ -f src/mapping.js ]; then
          rm src/mapping.js
        fi

    - name: Generate mapping.js from schema.jsm.json
      run: |
        echo "export const mapping = $(jq -c . < src/schema.jsm.json);" > src/mapping.js

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit and push changes
      run: |
        git add src/mapping.js
        git commit -m "Update mapping.js from schema.jsm.json"
        git push
      env:
        # The GITHUB_TOKEN is automatically provided by GitHub Actions.
        # It is used to authenticate and push the commit.
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

