name: Create JS file from JSON

on: [push, workflow_dispatch] 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install jq

    - name: Run script
      run: |
        rm src/mapping.js
        echo "export const mapping = $(jq -c . < src/schema.jsm.json);" > src/mapping.js