name: Create JS file from JSON

on: [push, workflow_dispatch] 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install jq

    - name: Run script
      run: |
        echo "module.exports = $(jq -c . < schema.jsm.json);" > mapping.js
        sed -i '1s/^/export const mapping = {\n/' mapping.js
        echo '};' >> mapping.js