name: Check for Leaks

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: TruffleHog OSS
      uses: trufflesecurity/trufflehog@v3.76.0
      with:
        # Repository path (default is ./)
        path: "./"
        # Start scanning from here (usually main branch)
        base: "main"
        # Scan commits until here (can be a branch or commit hash)
